### ISSUE TITLE
event registration (RSVP) exports - include individuals

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/clc-app-v2#35]
- update postgres schema
- persist new data
- write heroku data clip that pulls event and registrant info (name, email)

**Comment by jpowell** [comment]
@conrad-vanl might get your take on strategy for this... we'll be updating the database to include people info with RSVPs in a dataclip export

**Comment by gburgett** [comment]
@jpowell we don't have email addresses from some people last year, because we don't prompt them for it.  We currently only prompt for first and last name.  Do we need to also prompt for email?

Example:
Micah Bartig registered for Building the Body of Christ through Small Groups, but he never filled out his email in the profile section (and was never prompted to).  I can probably get his phone number from WMR rock but we just never stored his email.

If email is going to be needed for this report, we are going to need to prompt for it.

**Comment by conrad-vanl** [comment]
Everybody should have a phone number OR email

**Comment by jpowell** [comment]
I dont think we had a way to pull names, even, for RSVPs before. So that would help the CLC team to cross reference their data to fill out the holes
